### ISSUE TITLE
Notes on required JDK version

### ISSUE THREAD

**Issue by ZaLiTHkA** [welovecoding/editorconfig-netbeans#52]
This is awesome, it's a dream come true for me (ST3 fanboy working with Java developers). But being very much a Java noob myself, it did take me a little while to figure out why it wasn't working..

I didn't build from source, so I didn't notice the source and target rules in the Maven `pom.xml` were set to "1.8". I was running NetBeans 8.0.2 with JDK 1.7 and seeing `java.lang.UnsupportedClassVersionError: com/welovecoding/netbeans/plugin/editorconfig/filetype/FilenameResolver : Unsupported major.minor version 52.0` errors in my `messages.log` file.

Just a thought, but perhaps you should make a note in the project readme about the fact that this plugin requires JDK 1.8 to work properly?

**Comment by bennyn** [comment]
Hi @ZaLiTHkA, thank you for your feedback! We just updated our README file so that it displays the requirement for Java 8. Thanks for the hint.

By the way, you don't need to compile the plugin yourself. You can find all NetBeans modules (`*.nbm`) attached to our [releases](https://github.com/welovecoding/editorconfig-netbeans/releases). We just build v0.0.4. :smiley:

**Comment by ZaLiTHkA** [comment]
No worries, hope that saves someone else a headache..

I did install the `nbm` directly, which is why I didn't see the Java error at first.. Only figured that out when I went to check the project properties. :)
