### ISSUE TITLE
EditorConfig is only loaded on "Project Open"

### ISSUE THREAD

**Issue by bennyn** [welovecoding/editorconfig-netbeans#6]
EditorConfig is read & parsed when project is opened. In order to evaluate updated properties in the `.editorconfig` file, you have to close the project and open it again.

**Comment by Yserz** [comment]
With the current setup that's not possible since 
1. ProjectOpenedHook is triggered by opening a project
2. ProjectOpenedHook adds the ProjectChangeListener to the project

Since the ProjectChangeListener is not added to the already opened project any changes to the ProjectChangeListener won't work. Thus we need another mechanism to hook into projects. That's a bunch of work for a corner case since the plugin states that it needs a restart of the IDE where all projects will be opened and the listener will be attached.

**Comment by bennyn** [comment]
Ok, thanks for clarification!
