### ISSUE TITLE
Discussion: Requirement Java 8?

### ISSUE THREAD

**Issue by Yserz** [welovecoding/editorconfig-netbeans#62]
Should we go down with our requirements from Java 8 to Java 7?

Pro:
- NetBeans 8 runs with Java 7 and 8. If we go down to Java 7 the only requirement will be NetBeans 8
- No confusion for users

Contra:
- No Lambdas
- Some work to do

What do you think?

**Comment by ZaLiTHkA** [comment]
I would say yes.. Java 7 is still a very big player, I highly doubt that 8 will overtake it for a long time. I run it in testing environments, but our servers still use 6 and 7 for our production stuff.

Keeping in mind I say this coming from a software tester, non-developer type of mindset.. :)

**Comment by bennyn** [comment]
I do not like to develop things for outdated versions. Java 7 was first released in July 2011. This is soon **four years ago**. If it is not a big hassle to support it, then we should do it. But I do not think it is a priority. Especially among developers, it should go without saying, that your Java version should be up to date.

**Comment by junichi11** [comment]
**Java SE 7 End of Public Updates Notice:**
April 2015
https://www.java.com/en/download/faq/java_7.xml
http://www.oracle.com/technetwork/java/eol-135779.html

We should use Java 8 as far as possible since end of public updates comes soon. However, Java 7 may be required at the moment if we would like to publish a plugin and pass verifications on NetBeans Plugin Portal. (IMHO, It's no problem because we can just publish it if we don't have to pass them.)

**Comment by Yserz** [comment]
Good point! What are your thoughts about a middle way? For example we could deactivate the plugin if we detect Java 7 and show a tooltip/warning saying that the end of public updates is near and the plugin won't work with Java 7?

**Comment by junichi11** [comment]
@Yserz Please try to add a `ModuleInstall` class [1] (Sorry if I'm wrong).

We can add it like the following: New File > Category: Module Development > Installer / Activator 

[1] http://bits.netbeans.org/8.0/javadoc/org-openide-modules/org/openide/modules/ModuleInstall.html

**Comment by craiglondon** [comment]
I wish the memory leak with Java 8 would be fixed.   It's rediculous to start up Netbeans and it locks up over 500 MB of RAM

**Comment by bennyn** [comment]
Some users still don't notice that the plugin needs Java 8 (although it is written in our readme file, in our wiki and in the tooltip that we show on plugin installation), we should support Java 7.

We need to support Java 7 anyway in order to get certified for the official NetBeans Plugin Repository (thanks for the hint, @junichi11).

So I will rename this issue here and turn it into a real dev story for us. :sunglasses:
